"""The one-time seed bootstrap an organization admin runs (MC3-2): the seed project, the Infrastructure Manager
service account and its organization roles, and Workload Identity Federation for the repository's workflow."""

from app.providers.gcp.landing_zone.answers import GcpLandingZoneAnswers

SERVICES = ["config", "cloudresourcemanager", "orgpolicy", "iam", "iamcredentials", "serviceusage", "cloudbilling",
            "accesscontextmanager", "securityposture", "securitycenter", "networkconnectivity", "networksecurity",
            "compute", "logging", "backupdr", "essentialcontacts", "billingbudgets", "storage"]
ORGANIZATION_ROLES = ["roles/resourcemanager.folderAdmin", "roles/resourcemanager.projectCreator",
                      "roles/orgpolicy.policyAdmin", "roles/iam.denyAdmin", "roles/resourcemanager.tagAdmin",
                      "roles/resourcemanager.tagUser", "roles/compute.xpnAdmin", "roles/compute.orgFirewallPolicyAdmin",
                      "roles/accesscontextmanager.policyAdmin", "roles/securityposture.admin",
                      "roles/logging.configWriter", "roles/essentialcontacts.admin", "roles/networksecurity.admin",
                      "roles/billing.projectManager", "roles/config.agent", "roles/iam.serviceAccountUser"]
SERVICE_ACCOUNT = "lz-infra-manager"
POOL = "cloudinfra-github"


def seed_project(organization_name: str) -> str:
    return f"{organization_name}-lz-seed"


def seed_script(organization_name: str, answers: GcpLandingZoneAnswers) -> str:
    seed = seed_project(organization_name)
    account = f"{SERVICE_ACCOUNT}@{seed}.iam.gserviceaccount.com"
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by CloudInfra. Run once, as an organization admin, before the first apply:",
        "#   scripts/bootstrap-seed.sh <github-owner>/<repository>",
        "set -euo pipefail",
        'REPOSITORY="$1"',
        f'gcloud projects create "{seed}" --organization="{answers.organization_id}"',
        f'gcloud billing projects link "{seed}" --billing-account="{answers.billing_account}"',
        f'gcloud services enable {" ".join(f"{service}.googleapis.com" for service in SERVICES)} --project="{seed}"',
        (f'gcloud iam service-accounts create "{SERVICE_ACCOUNT}" --project="{seed}" '
        '--display-name="Landing zone (Infrastructure Manager)"'),
        *[f'gcloud organizations add-iam-policy-binding "{answers.organization_id}" '
          f'--member="serviceAccount:{account}" --role="{role}" --condition=None >/dev/null' for role in ORGANIZATION_ROLES],
        (f'gcloud billing accounts add-iam-policy-binding "{answers.billing_account}" '
        f'--member="serviceAccount:{account}" --role="roles/billing.user" >/dev/null'),
        f'gcloud iam workload-identity-pools create "{POOL}" --project="{seed}" --location=global',
        (f'gcloud iam workload-identity-pools providers create-oidc github --project="{seed}" --location=global '
        f'--workload-identity-pool="{POOL}" --issuer-uri="https://token.actions.githubusercontent.com" '
        '--attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" '
        '--attribute-condition="assertion.repository == \'${REPOSITORY}\'"'),
        (f'POOL_NAME="$(gcloud iam workload-identity-pools describe "{POOL}" --project="{seed}" --location=global '
        '--format="value(name)")"'),
        (f'gcloud iam service-accounts add-iam-policy-binding "{account}" --project="{seed}" '
        '--role="roles/iam.workloadIdentityUser" '
        '--member="principalSet://iam.googleapis.com/${POOL_NAME}/attribute.repository/${REPOSITORY}"'),
        'echo "Set these GitHub variables on the repository:"',
        'echo "  LZ_WORKLOAD_IDENTITY_PROVIDER=${POOL_NAME}/providers/github"',
        f'echo "  LZ_SERVICE_ACCOUNT={account}"',
        "",
    ]
    return "\n".join(lines)
