"""The one-time seed a tenant admin runs (MC5-2): the organization's management group, an app registration with a
federated credential for the repository's workflow, Owner on that management group only, and the billing role."""

import re

from app.providers.azure.landing_zone.answers import AzureLandingZoneAnswers

ENROLLMENT_ACCOUNT = re.compile(r"/enrollmentAccounts/[^/]+$")
SUBSCRIPTION_CREATOR = "a0bcee42-bf30-4d1b-926a-48d21664ef71"  # EA SubscriptionCreator billing role
ENVIRONMENT = "landing-zone"


def seed_script(organization: str, answers: AzureLandingZoneAnswers) -> str:
    group = f"/providers/Microsoft.Management/managementGroups/{organization}"
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by CloudInfra. Run once, as a tenant admin, before the first apply:",
        "#   scripts/bootstrap-seed.sh <github-owner>/<repository>",
        "set -euo pipefail",
        'REPOSITORY="$1"',
        f'az account management-group create --name "{organization}" --display-name "{organization}" || {{',
        '  echo "Creating a management group under the tenant root needs write access there: a Global Administrator',
        '  echo "can elevate access once (Entra ID > Properties > Access management for Azure resources)."; exit 1; }',
        f'APP_ID="$(az ad app create --display-name "{organization}-landing-zone" --query appId -o tsv)"',
        'OBJECT_ID="$(az ad sp create --id "$APP_ID" --query id -o tsv)"',
        'CREDENTIAL="$(mktemp)"',
        'cat > "$CREDENTIAL" <<JSON',
        ('{"name":"github-landing-zone","issuer":"https://token.actions.githubusercontent.com",'
         f'"subject":"repo:${{REPOSITORY}}:environment:{ENVIRONMENT}","audiences":["api://AzureADTokenExchange"]}}'),
        "JSON",
        'az ad app federated-credential create --id "$APP_ID" --parameters "@$CREDENTIAL"',
        ('az role assignment create --assignee-object-id "$OBJECT_ID" --assignee-principal-type ServicePrincipal '
         f'--role Owner --scope "{group}"'),
        *_billing(answers),
        'echo "Set these GitHub variables on the repository:"',
        'echo "  LZ_CLIENT_ID=$APP_ID"',
        f'echo "  LZ_TENANT_ID={answers.tenant_id}"',
        "",
    ]
    return "\n".join(lines)


def _billing(answers: AzureLandingZoneAnswers) -> list[str]:
    """EA: the SubscriptionCreator role on the enrollment account. MCA: granted by a billing admin (L1)."""
    scope = answers.billing_scope
    if not ENROLLMENT_ACCOUNT.search(scope):
        return [(f'echo "A billing admin grants the service principal $OBJECT_ID the Azure subscription creator role on '
                 f'{scope} (Cost Management + Billing > Access control)."')]
    body = ('{"properties": {"principalId": "\'"$OBJECT_ID"\'", '
            f'"principalTenantId": "{answers.tenant_id}", '
            f'"roleDefinitionId": "{scope}/billingRoleDefinitions/{SUBSCRIPTION_CREATOR}"}}}}')
    return [(f'az rest --method put --url "https://management.azure.com{scope}/billingRoleAssignments/$(uuidgen)'
             f'?api-version=2019-10-01-preview" --body \'{body}\'')]
