import json
from abc import ABC, abstractmethod

import yaml

from app.landing_zone.cloudformation.accounts import AccountsStack
from app.landing_zone.cloudformation.base import StackContext, StackRenderer
from app.landing_zone.cloudformation.bootstrap import BootstrapStack
from app.landing_zone.cloudformation.foundation import FoundationStack
from app.landing_zone.cloudformation.network import NetworkStack
from app.landing_zone.cloudformation.references import pascal
from app.landing_zone.cloudformation.structure import StructureStack
from app.landing_zone.design import LandingZoneDesign, OrgCatalog, OuNode
from app.landing_zone.designer import network_host_suffix
from app.landing_zone.diagram import OuDiagramRenderer
from app.synth.render import NoAliasDumper

STACKS: list[StackRenderer] = [FoundationStack(), StructureStack(), AccountsStack(), NetworkStack(), BootstrapStack()]
STACK_FILES = {stack.name: f"stacks/{stack.name}.yaml" for stack in STACKS}
POLICY_TYPES = ["SERVICE_CONTROL_POLICY", "RESOURCE_CONTROL_POLICY", "TAG_POLICY", "BACKUP_POLICY",
                "AISERVICES_OPT_OUT_POLICY"]


class BundleFile(ABC):
    """One or more files of the landing-zone-infra repository."""

    @abstractmethod
    def render(self, context: StackContext) -> dict[str, str]:
        ...


class StackFiles(BundleFile):
    def __init__(self, stacks: list[StackRenderer]):
        self._stacks = stacks

    def render(self, context):
        return {STACK_FILES[stack.name]: yaml.dump(stack.render(context), Dumper=NoAliasDumper, sort_keys=False,
                                                   width=120) for stack in self._stacks}


class DesignJson(BundleFile):
    def render(self, context):
        design = context.design
        document = {"answers": design.answers.model_dump(mode="json"), "ous": [_ou_json(ou) for ou in design.root_ous]}
        return {"design.json": json.dumps(document, indent=2) + "\n"}


class DiagramFiles(BundleFile):
    def render(self, context):
        renderer = OuDiagramRenderer()
        return {"docs/ou-structure.svg": renderer.svg(context.design),
                "docs/ou-structure.mmd": renderer.mermaid(context.design)}


class ApplyScript(BundleFile):
    """Runs the stacks in order. Steps CloudFormation cannot express (policy types, Control Tower ids, the
    Network account role) are AWS CLI calls between the stacks."""

    def render(self, context):
        answers = context.design.answers
        sandbox = next(ou for ou in context.design.environment_ous() if ou.tier == "sandbox")
        regions = " ".join(answers.governed_regions)
        lines = [
            "#!/usr/bin/env bash",
            "# Generated by CloudInfra. Applies the landing zone from the management account, in order.",
            "set -euo pipefail",
            f'REGION="${{AWS_HOME_REGION:-{answers.home_region}}}"',
            'MANAGEMENT_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"',
            ('output() { aws cloudformation describe-stacks --region "$1" --stack-name "$2" '
            '--query "Stacks[0].Outputs[?OutputKey==\'$3\'].OutputValue" --output text; }'),
            "# Templates over CloudFormation's 51,200-byte inline limit must come from S3: one private bucket per",
            "# account and region.",
            "template_bucket() {",
            '  local bucket="cloudinfra-lz-templates-$(aws sts get-caller-identity --query Account --output text)-$1"',
            '  if ! aws s3api head-bucket --bucket "$bucket" >/dev/null 2>&1; then',
            '    if [ "$1" = "us-east-1" ]; then aws s3api create-bucket --bucket "$bucket" --region "$1" >/dev/null',
            ('    else aws s3api create-bucket --bucket "$bucket" --region "$1" '
            '--create-bucket-configuration LocationConstraint="$1" >/dev/null; fi'),
            ('    aws s3api put-public-access-block --bucket "$bucket" --public-access-block-configuration '
            'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true'),
            ('    aws s3api put-bucket-encryption --bucket "$bucket" --server-side-encryption-configuration '
            '\'{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}\''),
            "  fi",
            '  echo "$bucket"',
            "}",
            "",
            'echo "1/5 Organization, Control Tower roles, Log Archive, Audit and the landing zone"',
            (f'aws cloudformation deploy --region "$REGION" --s3-bucket "$(template_bucket "$REGION")" --stack-name lz-foundation --template-file {STACK_FILES["lz-foundation"]} '
            "--capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset"),
            'ORG_ID="$(output "$REGION" lz-foundation OrganizationId)"',
            'ROOT_ID="$(output "$REGION" lz-foundation RootId)"',
            "",
            'echo "Enable organization policy types"',
            f"for type in {' '.join(POLICY_TYPES)}; do",
            ('  aws organizations enable-policy-type --root-id "$ROOT_ID" --policy-type "$type" >/dev/null 2>&1 '
            '|| echo "  $type already enabled"'),
            "done",
            "",
            'echo "Resolve the OUs and baselines Control Tower created"',
            ('ou_named() { aws organizations list-organizational-units-for-parent --parent-id "$ROOT_ID" '
            '--query "OrganizationalUnits[?Name==\'$1\'].Id" --output text; }'),
            ('baseline_named() { aws controltower list-baselines --region "$REGION" '
            '--query "baselines[?name==\'$1\'].arn" --output text; }'),
            'SECURITY_OU_ID="$(ou_named Security)"',
            f'SANDBOX_OU_ID="$(ou_named "{sandbox.name}")"',
            'BASELINE_ARN="$(baseline_named AWSControlTowerBaseline)"',
            ('IDENTITY_CENTER_ARN="$(aws controltower list-enabled-baselines --region "$REGION" '
            '--query "enabledBaselines[?baselineIdentifier==\'$(baseline_named IdentityCenterBaseline)\'].arn" --output text)"'),
            "",
            'echo "2/5 OUs, policies, baselines and controls"',
            (f'aws cloudformation deploy --region "$REGION" --s3-bucket "$(template_bucket "$REGION")" --stack-name lz-structure --template-file {STACK_FILES["lz-structure"]} '
            '--no-fail-on-empty-changeset --parameter-overrides SecurityOuId="$SECURITY_OU_ID" SandboxOuId="$SANDBOX_OU_ID" '
            'ControlTowerBaselineArn="$BASELINE_ARN" IdentityCenterEnabledBaselineArn="$IDENTITY_CENTER_ARN"'),
            "",
            'echo "3/5 Accounts through Account Factory"',
            (f'aws cloudformation deploy --region "$REGION" --s3-bucket "$(template_bucket "$REGION")" --stack-name lz-accounts --template-file {STACK_FILES["lz-accounts"]} '
            '--no-fail-on-empty-changeset --parameter-overrides SecurityOuId="$SECURITY_OU_ID" SandboxOuId="$SANDBOX_OU_ID"'),
            "",
            'echo "4/5 Network (shared VPCs, Transit Gateway, egress and inspection) in every governed region"',
            *self._network_parameters(context),
            *self._assume_network_host(context),
            f"for region in {regions}; do",
            (f'  aws cloudformation deploy --region "$region" --s3-bucket "$(template_bucket "$region")" --stack-name lz-network --template-file {STACK_FILES["lz-network"]} '
            '--no-fail-on-empty-changeset --parameter-overrides "${NETWORK_PARAMETERS[@]}"'),
            "done",
            "unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN",
            "",
            'echo "5/5 Account bootstrap StackSet"',
            (f'aws cloudformation deploy --region "$REGION" --s3-bucket "$(template_bucket "$REGION")" --stack-name lz-bootstrap --template-file {STACK_FILES["lz-bootstrap"]} '
            '--no-fail-on-empty-changeset --parameter-overrides PlatformAccountId="$PLATFORM_ACCOUNT_ID" '
            'SandboxOuId="$SANDBOX_OU_ID"'),
            'echo "Landing zone applied."',
        ]
        return {"scripts/apply.sh": "\n".join(lines) + "\n"}

    def _network_parameters(self, context: StackContext) -> list[str]:
        infrastructure = next(ou for ou in context.design.walk() if ou.kind == "infrastructure")
        lines = ["NETWORK_PARAMETERS=("]
        for ou in [*context.design.environment_ous(), infrastructure]:
            key = f"Ou{pascal(ou.key)}Arn"
            if ou.created_by_control_tower:
                lines.append(f'  "{key}=arn:aws:organizations::$MANAGEMENT_ACCOUNT_ID:ou/$ORG_ID/$SANDBOX_OU_ID"')
            else:
                lines.append(f'  "{key}=$(output "$REGION" lz-structure {key})"')
        return [*lines, ")"]

    def _assume_network_host(self, context: StackContext) -> list[str]:
        if network_host_suffix(context.design.answers) is None:
            return ["# No Network or Shared Services account: the shared VPCs live in the management account."]
        return [
            'NETWORK_ACCOUNT_ID="$(output "$REGION" lz-accounts NetworkAccountId)"',
            ('CREDENTIALS="$(aws sts assume-role --role-arn "arn:aws:iam::$NETWORK_ACCOUNT_ID:role/AWSControlTowerExecution" '
            '--role-session-name landing-zone --query Credentials --output json)"'),
            'export AWS_ACCESS_KEY_ID="$(echo "$CREDENTIALS" | python3 -c "import json,sys;print(json.load(sys.stdin)[\'AccessKeyId\'])")"',
            'export AWS_SECRET_ACCESS_KEY="$(echo "$CREDENTIALS" | python3 -c "import json,sys;print(json.load(sys.stdin)[\'SecretAccessKey\'])")"',
            'export AWS_SESSION_TOKEN="$(echo "$CREDENTIALS" | python3 -c "import json,sys;print(json.load(sys.stdin)[\'SessionToken\'])")"',
        ]


class DeployWorkflow(BundleFile):
    TEXT = """name: deploy-landing-zone
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
concurrency:
  group: landing-zone
  cancel-in-progress: false
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: management
    steps:
      - uses: actions/checkout@v4
      - name: Lint templates
        run: pip install cfn-lint && cfn-lint stacks/*.yaml
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.MANAGEMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_HOME_REGION }}
          role-duration-seconds: 14400
      - name: Apply landing zone
        run: ./scripts/apply.sh
        env:
          AWS_HOME_REGION: ${{ vars.AWS_HOME_REGION }}
          PLATFORM_ACCOUNT_ID: ${{ vars.PLATFORM_ACCOUNT_ID }}
"""

    def render(self, context):
        return {".github/workflows/deploy-landing-zone.yml": self.TEXT}


class ControlsDocument(BundleFile):
    """The Control Tower controls on each OU, for auditors, with the frameworks the catalog maps them to."""

    def render(self, context):
        lines = [f"# Control Tower controls: {context.design.answers.organization_name}", "",
                 "Preventive controls are enabled on the top-most OU and inherited below it; detective and proactive",
                 "controls are enabled on every OU they apply to.", ""]
        for ou in context.design.walk():
            enabled = context.guardrails.controls.get(ou.key, [])
            if enabled:
                lines += [f"## {ou.label}", "", "| Control | Name | Behavior | Severity | Packs | Frameworks |",
                          "|---|---|---|---|---|---|", *map(_control_row, enabled), ""]
        return {"docs/controls.md": "\n".join(lines)}


class Readme(BundleFile):
    def render(self, context):
        design = context.design
        lines = [f"# {design.answers.organization_name} landing zone", "",
                 "Generated by the CloudInfra platform from the approved landing zone design. Change it through the",
                 "platform's Landing zone workflow; every change is planned, approved by a second admin and committed here.",
                 "", "![OU structure](docs/ou-structure.svg)", "", "## Stacks (applied in this order by scripts/apply.sh)", ""]
        lines += [f"{index}. `{path}`: {stack.description}" for index, stack in enumerate(STACKS, start=1)
                  for path in [STACK_FILES[stack.name]]]
        lines += ["", "## OU structure", "", *[line for ou in design.root_ous for line in _tree_lines(ou, 0)], ""]
        return {"README.md": "\n".join(lines)}


CLOUDFORMATION_RESOURCE_LIMIT = 500


class StackSizeRule:
    """CloudFormation allows 500 resources per stack; a bigger stack would only fail at deploy time."""

    def problems(self, design: LandingZoneDesign, catalog: OrgCatalog) -> list[str]:
        context = StackContext.build(design, catalog)
        sizes = [(stack.name, len(stack.render(context)["Resources"])) for stack in STACKS]
        return [f"Stack {name} would have {size} resources; CloudFormation allows {CLOUDFORMATION_RESOURCE_LIMIT} per "
                "stack. Remove OUs or control packs, or split the design."
                for name, size in sizes if size > CLOUDFORMATION_RESOURCE_LIMIT]


class LandingZoneBundle:
    def __init__(self, files: list[BundleFile]):
        self._files = files

    @classmethod
    def default(cls) -> "LandingZoneBundle":
        return cls([StackFiles(STACKS), DesignJson(), DiagramFiles(), ControlsDocument(), ApplyScript(), DeployWorkflow(),
                    Readme()])

    def render(self, design: LandingZoneDesign, catalog: OrgCatalog) -> dict[str, str]:
        context = StackContext.build(design, catalog)
        files: dict[str, str] = {}
        for bundle_file in self._files:
            files.update(bundle_file.render(context))
        return files


def _control_row(enabled) -> str:
    control = enabled.control
    return (f"| `{control.id}` | {control.name} | {control.behavior} | {control.severity} | {', '.join(enabled.packs)} "
            f"| {', '.join(control.frameworks) or 'not refreshed'} |")


def _ou_json(ou: OuNode) -> dict:
    return {"name": ou.name, "kind": ou.kind, "environment": ou.environment,
            "accounts": [account.name for account in ou.accounts], "children": [_ou_json(child) for child in ou.children]}


def _tree_lines(ou: OuNode, depth: int) -> list[str]:
    accounts = f" ({', '.join(account.name for account in ou.accounts)})" if ou.accounts else ""
    return [f"{'  ' * depth}- **{ou.label}**{accounts}", *[line for child in ou.children for line in _tree_lines(child, depth + 1)]]
