from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from app.adapters.ports import AwsPort, BootstrapOutputs, BootstrapRequest, GitHubPort
from app.projects.readback import KIND, repository_name
from app.provisioning.topology import RegionTopology
from app.readback.subjects import ownership_properties
from app.synth.request import ProjectRequest

COMMIT_MESSAGE = "Initial infrastructure generated by CloudInfra"
ARTIFACT_BUCKET_PATTERN = "cloudinfra-artifacts-{region}"
REGION_SUFFIXES = ("", "_SECONDARY")


@dataclass
class ProvisioningContext:
    request_id: str
    request: ProjectRequest
    owner: str
    files: dict[str, str]
    accounts: dict[str, str]
    topology: RegionTopology
    tags: dict[str, str]
    github: GitHubPort
    aws: AwsPort
    networks: dict[tuple[str, str], dict] = field(default_factory=dict)
    bootstrap_outputs: dict[tuple[str, str], BootstrapOutputs] = field(default_factory=dict)
    repository_created: bool = False
    commit_sha: str | None = None

    @property
    def repository_name(self) -> str:
        return repository_name(self.request.project_name)

    @property
    def repository_full_name(self) -> str:
        return f"{self.owner}/{self.repository_name}"


class ProvisioningStep(ABC):
    """One unit of provisioning with an undo action. New steps plug into ProvisioningPlanner."""

    name: str

    @abstractmethod
    def execute(self, context: ProvisioningContext) -> None:
        ...

    def compensate(self, context: ProvisioningContext) -> None:
        return None


class CreateRepositoryStep(ProvisioningStep):
    name = "create_repository"

    def execute(self, context):
        context.repository_created = context.github.create_repository(context.owner, context.repository_name,
                                                                      marker=context.request_id)
        context.github.set_repository_properties(context.owner, context.repository_name,
                                                 ownership_properties(KIND, context.request.project_name))

    def compensate(self, context):
        if context.repository_created:
            context.github.delete_repository(context.owner, context.repository_name)


class BootstrapAccountStep(ProvisioningStep):
    def __init__(self, environment: str, region: str):
        self.environment = environment
        self.region = region
        self.name = f"bootstrap:{environment}:{region}"

    def execute(self, context):
        context.bootstrap_outputs[(self.environment, self.region)] = context.aws.ensure_bootstrap_stack(
            self._request(context))

    def compensate(self, context):
        context.aws.delete_bootstrap_stack(self._request(context))

    def _request(self, context: ProvisioningContext) -> BootstrapRequest:
        return BootstrapRequest(account_id=context.accounts[self.environment], region=self.region,
                                project=context.request.project_name, repository=context.repository_full_name,
                                environment=self.environment)


class RepositoryVariables:
    def __init__(self, context: ProvisioningContext):
        self._context = context

    def as_dict(self) -> dict[str, str]:
        tags = self._context.tags
        request = self._context.request
        return {"PROJECT_NAME": request.project_name, "ORG_PORTFOLIO": tags["org:portfolio"],
                "ORG_PRODUCT": tags["org:product"], "ORG_COST_CENTER": tags["org:cost-center"],
                "ORG_DATA_CLASSIFICATION": tags["org:data-classification"],
                "RESILIENCE_MODE": request.resilience.mode, "ENVIRONMENT_ORDER": ",".join(request.environments)}


class EnvironmentVariables:
    """GitHub environment variables: the only place account numbers, roles and regions appear."""

    def __init__(self, context: ProvisioningContext, environment: str):
        self._context = context
        self._environment = environment

    def as_dict(self) -> dict[str, str]:
        primary, *secondaries = self._context.topology.regions_for(self._environment)
        outputs = self._context.bootstrap_outputs[(self._environment, primary)]
        variables = {"ENVIRONMENT_NAME": self._environment, "AWS_ACCOUNT_ID": self._context.accounts[self._environment],
                     "AWS_PRIMARY_REGION": primary, "AWS_ROLE_ARN": outputs.deploy_role_arn,
                     "CFN_EXEC_ROLE_ARN": outputs.cfn_execution_role_arn,
                     "ARTIFACT_BUCKET": ARTIFACT_BUCKET_PATTERN.format(region=primary)}
        for secondary in secondaries:
            variables.update(self._secondary(secondary))
        for region, suffix in zip([primary, *secondaries], REGION_SUFFIXES, strict=False):
            variables.update(self._network(region, suffix))
        return variables

    def _network(self, region: str, suffix: str) -> dict[str, str]:
        network = self._context.networks.get((self._environment, region))
        if network is None:
            return {}
        return {f"VPC_ID{suffix}": network["vpc_id"],
                f"PRIVATE_SUBNET_IDS{suffix}": ",".join(network["private_subnet_ids"]),
                f"ORG_SECURITY_GROUP_IDS{suffix}": ",".join(network["security_group_ids"]),
                f"ORG_PRIVATE_CIDR{suffix}": network["cidr"]}

    def _secondary(self, region: str) -> dict[str, str]:
        return {"AWS_SECONDARY_REGION": region,
                "ACTIVATION_STATE_SECONDARY": self._context.topology.secondary_activation(),
                "ARTIFACT_BUCKET_SECONDARY": ARTIFACT_BUCKET_PATTERN.format(region=region)}


class ConfigureEnvironmentsStep(ProvisioningStep):
    name = "configure_environments"

    def execute(self, context):
        context.github.set_repository_variables(context.owner, context.repository_name,
                                                RepositoryVariables(context).as_dict())
        for environment in context.request.environments:
            context.github.set_environment(context.owner, context.repository_name, environment,
                                           EnvironmentVariables(context, environment).as_dict())


class CommitFilesStep(ProvisioningStep):
    name = "commit_files"

    def execute(self, context):
        context.commit_sha = context.github.commit_files(context.owner, context.repository_name, context.files,
                                                         COMMIT_MESSAGE)


class ProvisioningPlanner:
    """Orders the steps: repository, AWS trust in every account/region, GitHub settings, then one commit."""

    def steps_for(self, context: ProvisioningContext) -> list[ProvisioningStep]:
        bootstrap = [BootstrapAccountStep(environment, region) for environment in context.request.environments
                     for region in context.topology.regions_for(environment)]
        return [CreateRepositoryStep(), *bootstrap, ConfigureEnvironmentsStep(), CommitFilesStep()]
