import json
from abc import ABC, abstractmethod

from app.synth.request import ProjectRequest


class FileRenderer(ABC):
    """Produces one or more files of the generated infrastructure repository."""

    @abstractmethod
    def render(self, request: ProjectRequest, template: dict) -> dict[str, str]:
        ...


class InfraJsonRenderer(FileRenderer):
    def render(self, request, template):
        return {"infra.json": json.dumps(request.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"}


class ReadmeRenderer(FileRenderer):
    def __init__(self, document_file: str):
        self._document_file = document_file

    def render(self, request, template):
        ownership = request.ownership
        lines = [
            f"# {request.project_name}-infra",
            "",
            "Infrastructure generated by the CloudInfra platform. Change it through the platform UI",
            f"(Change infrastructure), which regenerates `{self._document_file}` from `infra.json`.",
            "",
            f"- Portfolio: `{ownership.portfolio_id}`",
            f"- Product: `{ownership.product_id}`",
            f"- Data classification: `{ownership.data_classification}`",
            f"- Resilience: `{request.resilience.mode}` ({', '.join(request.resilience.selected_regions())})",
            f"- Environments: {', '.join(request.environments)}",
            "",
            "QA/STAGE and PROD are applied by the platform release executor after reviewer approval.",
            "",
        ]
        return {"README.md": "\n".join(lines)}


class RepositoryBundle:
    """The files of a generated repository: each provider lists its renderers, plus the neutral ones above."""

    def __init__(self, renderers: list[FileRenderer]):
        self._renderers = renderers

    def render(self, request: ProjectRequest, template: dict) -> dict[str, str]:
        files: dict[str, str] = {}
        for renderer in self._renderers:
            files.update(renderer.render(request, template))
        return files
