import copy


class DuplicateLogicalIdError(ValueError):
    pass


class Template:
    """Mutable CloudFormation template under construction; to_dict() returns an independent snapshot."""

    FORMAT_VERSION = "2010-09-09"
    DESCRIPTION = "Generated by CloudInfra. Do not edit by hand; change infra.json and regenerate."

    def __init__(self):
        self._metadata: dict = {}
        self._parameters: dict = {}
        self._conditions: dict = {}
        self._resources: dict = {}
        self._outputs: dict = {}

    def set_metadata(self, metadata: dict) -> None:
        self._metadata = metadata

    def add_parameter(self, name: str, body: dict) -> None:
        self._parameters[name] = body

    def add_condition(self, name: str, body: dict) -> None:
        self._conditions[name] = body

    def add_output(self, name: str, body: dict) -> None:
        self._outputs[name] = body

    def add_resource(self, logical_id: str, body: dict) -> None:
        if logical_id in self._resources:
            raise DuplicateLogicalIdError(logical_id)
        self._resources[logical_id] = body

    def resource(self, logical_id: str) -> dict:
        return self._resources[logical_id]

    def has_resource_type(self, type_name: str) -> bool:
        return any(body["Type"] == type_name for body in self._resources.values())

    def to_dict(self) -> dict:
        sections = {"AWSTemplateFormatVersion": self.FORMAT_VERSION, "Description": self.DESCRIPTION}
        optional = {"Metadata": self._metadata, "Parameters": self._parameters, "Conditions": self._conditions}
        sections.update({name: body for name, body in optional.items() if body})
        sections["Resources"] = self._resources
        sections.update({"Outputs": self._outputs} if self._outputs else {})
        return copy.deepcopy(sections)
