import copy


class DuplicateLogicalIdError(ValueError):
    pass


class Template:
    """Mutable CloudFormation template under construction; to_dict() returns an independent snapshot."""

    FORMAT_VERSION = "2010-09-09"
    DESCRIPTION = "Generated by CloudInfra. Do not edit by hand; change infra.json and regenerate."

    def __init__(self):
        self._metadata: dict = {}
        self._parameters: dict = {}
        self._conditions: dict = {}
        self._resources: dict = {}
        self._outputs: dict = {}

    def set_metadata(self, metadata: dict) -> None:
        self._metadata = metadata

    def add_parameter(self, name: str, body: dict) -> None:
        self._parameters[name] = body

    def add_condition(self, name: str, body: dict) -> None:
        self._conditions[name] = body

    def add_output(self, name: str, body: dict) -> None:
        self._outputs[name] = body

    def add_resource(self, logical_id: str, body: dict) -> None:
        if logical_id in self._resources:
            raise DuplicateLogicalIdError(logical_id)
        self._resources[logical_id] = body

    def resource(self, logical_id: str) -> dict:
        return self._resources[logical_id]

    def has_resource_type(self, type_name: str) -> bool:
        return any(body["Type"] == type_name for body in self._resources.values())

    def to_dict(self) -> dict:
        sections = {"AWSTemplateFormatVersion": self.FORMAT_VERSION, "Description": self.DESCRIPTION}
        optional = {"Metadata": self._metadata, "Parameters": self._parameters, "Conditions": self._used_conditions()}
        sections.update({name: body for name, body in optional.items() if body})
        sections["Resources"] = self._resources
        sections.update({"Outputs": self._outputs} if self._outputs else {})
        return copy.deepcopy(sections)

    def _used_conditions(self) -> dict:
        """Conditions referenced from resources or outputs, directly or through other conditions."""
        used = ConditionReferences(self._conditions).reachable_from([self._resources, self._outputs])
        return {name: body for name, body in self._conditions.items() if name in used}


class ConditionReferences:
    """Finds condition names used via a "Condition" key or as the first argument of Fn::If."""

    def __init__(self, conditions: dict):
        self._conditions = conditions

    def reachable_from(self, roots: list) -> set[str]:
        used: set[str] = set()
        pending = self._direct(roots)
        while pending:
            name = pending.pop()
            if name in used or name not in self._conditions:
                continue
            used.add(name)
            pending |= self._direct([self._conditions[name]])
        return used

    def _direct(self, nodes: list) -> set[str]:
        found: set[str] = set()
        stack = list(nodes)
        while stack:
            node = stack.pop()
            if isinstance(node, dict):
                found |= self._named(node)
                stack.extend(node.values())
            elif isinstance(node, list):
                stack.extend(node)
        return found

    @staticmethod
    def _named(node: dict) -> set[str]:
        names = {node["Condition"]} if isinstance(node.get("Condition"), str) else set()
        condition_if = node.get("Fn::If")
        if isinstance(condition_if, list) and condition_if and isinstance(condition_if[0], str):
            names.add(condition_if[0])
        return names
