"""landing zone designs

Revision ID: 148de0163524
Revises: 16ee986b7094
Create Date: 2026-10-04 01:54:38.876776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148de0163524'
down_revision: Union[str, Sequence[str], None] = '16ee986b7094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_zone_designs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('submitted_by', sa.String(length=128), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('repository', sa.String(length=256), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('accounts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landing_zone_designs')
    # ### end Alembic commands ###
