"""organization networks

Revision ID: 16ee986b7094
Revises: a13679f80f5f
Create Date: 2026-10-03 21:53:06.526632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ee986b7094'
down_revision: Union[str, Sequence[str], None] = 'a13679f80f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('cidr', sa.String(length=43), nullable=False),
    sa.Column('private_subnet_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('security_group_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_account_id'), 'networks', ['account_id'], unique=False)
    op.add_column('organization_settings', sa.Column('attach_compute_to_vpc', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'attach_compute_to_vpc')
    op.drop_index(op.f('ix_networks_account_id'), table_name='networks')
    op.drop_table('networks')
    # ### end Alembic commands ###
