"""releases and decisions

Revision ID: a13679f80f5f
Revises: f444c8bc435e
Create Date: 2026-10-03 21:29:33.528926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13679f80f5f'
down_revision: Union[str, Sequence[str], None] = 'f444c8bc435e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('environment_id', sa.String(length=16), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('artifact_digest', sa.String(length=128), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('gate_findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('execution_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_project_name'), 'releases', ['project_name'], unique=False)
    op.create_table('release_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_decisions')
    op.drop_index(op.f('ix_releases_project_name'), table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
