import difflib
import json
from abc import ABC, abstractmethod
from dataclasses import dataclass

from app.adapters.ports import RepositorySnapshot
from app.readback.manifest import MANIFEST_PATH, Manifest, ManifestError, ManifestSigner
from app.readback.subjects import ReadBackSubject, ownership_properties

BLOCKING = "blocking"
WARNING = "warning"
SHORT_SHA = 7


@dataclass(frozen=True)
class ChangedFile:
    path: str
    diff: str | None = None


@dataclass(frozen=True)
class Finding:
    check: str
    severity: str
    message: str
    files: tuple[ChangedFile, ...] = ()

    @property
    def blocking(self) -> bool:
        return self.severity == BLOCKING

    def as_dict(self) -> dict:
        return {"check": self.check, "severity": self.severity, "message": self.message,
                "files": [{"path": changed.path, "diff": changed.diff} for changed in self.files]}


@dataclass
class ReadBackContext:
    """What the checks share: the repository as it is now, and what earlier checks established."""

    subject: ReadBackSubject
    signer: ManifestSigner
    snapshot: RepositorySnapshot | None
    properties: dict[str, str]
    manifest: Manifest | None = None
    request: dict | None = None


class ReadBackCheck(ABC):
    """One question about a repository before its design is loaded back. New checks plug into RepositoryReader."""

    name: str

    @abstractmethod
    def run(self, context: ReadBackContext) -> list[Finding]:
        ...

    def _block(self, message: str, files: tuple[ChangedFile, ...] = ()) -> list[Finding]:
        return [Finding(self.name, BLOCKING, message, files)]

    def _warn(self, message: str, files: tuple[ChangedFile, ...] = ()) -> list[Finding]:
        return [Finding(self.name, WARNING, message, files)]


class RepositoryExistsCheck(ReadBackCheck):
    name = "repository"

    def run(self, context):
        if context.snapshot is None:
            return self._block(f"Repository {context.subject.repository} does not exist.")
        return []


class PropertiesCheck(ReadBackCheck):
    name = "properties"

    def run(self, context):
        subject = context.subject
        expected = ownership_properties(subject.kind, subject.id)
        if any(context.properties.get(key) != value for key, value in expected.items()):
            return self._block(f"Repository {subject.repository} is not marked as generated by the platform for "
                               f"{subject.kind} {subject.id}.")
        return []


class ManifestSignatureCheck(ReadBackCheck):
    name = "manifest"

    def run(self, context):
        text = context.snapshot.files.get(MANIFEST_PATH)
        if text is None:
            return self._block(f"The repository has no {MANIFEST_PATH}: it was not generated by the platform, or "
                               "was generated before read-back existed. Approve a new version to stamp it.")
        try:
            context.manifest = context.signer.verify(json.loads(text))
        except ValueError:
            return self._block(f"{MANIFEST_PATH} is not valid JSON.")
        except ManifestError as error:
            return self._block(str(error))
        return []


class RecordCheck(ReadBackCheck):
    name = "record"

    def run(self, context):
        manifest, subject = context.manifest, context.subject
        if (manifest.kind, manifest.id, manifest.revision) != (subject.kind, subject.id, subject.revision):
            return self._block(f"The manifest describes {manifest.kind} {manifest.id} revision {manifest.revision}, "
                               f"but the platform's record is {subject.kind} {subject.id} revision {subject.revision}.")
        return []


class IntegrityCheck(ReadBackCheck):
    """Every generated file must be byte for byte what the platform committed (decision RB1: strict)."""

    name = "integrity"

    def run(self, context):
        files = context.snapshot.files
        changed = [path for path, digest in sorted(context.manifest.files.items())
                   if path not in files or Manifest.digest(files[path]) != digest]
        if not changed:
            return []
        # The platform's record regenerates the committed content while the generator is unchanged; then a diff shows
        # exactly what was edited by hand.
        generated = context.subject.regenerate(context.subject.recorded_request())
        return self._block("Files were edited outside the platform. Revert them in GitHub, or change the design here.",
                           tuple(ChangedFile(path, self._diff(context, generated, path)) for path in changed))

    def _diff(self, context: ReadBackContext, generated: dict[str, str], path: str) -> str | None:
        actual, expected = context.snapshot.files.get(path), generated.get(path)
        if actual is None or expected is None or Manifest.digest(expected) != context.manifest.files[path]:
            return None
        return "".join(difflib.unified_diff(expected.splitlines(keepends=True), actual.splitlines(keepends=True),
                                            fromfile=f"generated/{path}", tofile=f"repository/{path}"))


class InputCheck(ReadBackCheck):
    name = "input"

    def run(self, context):
        input_file = context.manifest.input
        try:
            context.request = context.subject.parse_input(context.snapshot.files[input_file])
        except ValueError as error:
            return self._block(f"{input_file} can no longer be read: {error}")
        return []


class HeadCheck(ReadBackCheck):
    name = "head"

    def run(self, context):
        head, recorded = context.snapshot.commit_sha, context.subject.recorded_commit
        if head == recorded:
            return []
        return self._warn(f"The repository has commits the platform did not make (HEAD {head[:SHORT_SHA]}, the "
                          f"platform's last commit {recorded[:SHORT_SHA] if recorded else 'unknown'}). They do not "
                          "change generated files.")


class RegenerationCheck(ReadBackCheck):
    name = "regeneration"

    def run(self, context):
        expected = context.manifest.files
        regenerated = {path: Manifest.digest(content)
                       for path, content in context.subject.regenerate(context.request).items()}
        changed = sorted(path for path in {*expected, *regenerated} if expected.get(path) != regenerated.get(path))
        if not changed:
            return []
        return self._warn(f"The generator, registry or control catalog changed since this commit: saving a change "
                          f"will also update {len(changed)} generated file(s).",
                          tuple(ChangedFile(path) for path in changed))
