from abc import ABC, abstractmethod

PROPERTY_MANAGED = "cloudinfra-managed"
PROPERTY_KIND = "cloudinfra-kind"
PROPERTY_ID = "cloudinfra-id"


def ownership_properties(kind: str, id: str) -> dict[str, str]:
    """The repository custom properties that mark a repository as generated by the platform (discovery only)."""
    return {PROPERTY_MANAGED: "true", PROPERTY_KIND: kind, PROPERTY_ID: id}


class ReadBackSubject(ABC):
    """Something the platform generates into a repository and can load back: a project or the landing zone."""

    kind: str
    input_file: str

    @property
    @abstractmethod
    def id(self) -> str:
        ...

    @property
    @abstractmethod
    def revision(self) -> int:
        ...

    @property
    @abstractmethod
    def repository(self) -> str:
        ...

    @property
    @abstractmethod
    def recorded_commit(self) -> str | None:
        """The last commit the platform made, as recorded in the database."""

    @abstractmethod
    def recorded_request(self) -> dict:
        """The input as recorded in the database."""

    @abstractmethod
    def parse_input(self, text: str) -> dict:
        """The input file's request, validated against today's model. Raises ValueError when it no longer fits."""

    @abstractmethod
    def regenerate(self, request: dict) -> dict[str, str]:
        """The files today's generator produces from the request, without the manifest."""

    def identity(self) -> dict:
        return {"kind": self.kind, "id": self.id, "revision": self.revision}
